# \> My Songs for You

---
title: "My Songs for You"
format: html
editor: visual
---

> *Songs I have personal connection with.*

## To Life Itself?

## Sebelah Mata

{{< video https://youtu.be/u5aHyZV0CTI?si=zNwUnuZnOY9taS2E>}}

> Tapi sebelah mataku yang lain menyadari
>
> Gelap adalah teman setia
>
> Dari waktu-waktu yang hilang

Bukan genre lagu yang biasanya saya nikmati, tapi atmosfernya sangat menghanyutkan. Entah mengapa ini jadi salah satu lagu yang paling sering saya putar di tahun 2024. Jadi pengingat bahwa tidak semua hal harus selalu ceria dan penuh semangat.

## For Myself

## In My Mouth

{{< video https://youtu.be/cIi4SxZ0IC8?si=EeUQOrJCeDpnrkRK>}}

> I don't feel like I can be anything more than this
>
> I don't really want to be anything more than this
>
> I just wanna be whatever you want me to be
>
> I don't wanna have a soul

Lagu ini salah satu tipe musik yang saya sukai dan ada kenangan tersendiri. Lagunya menyajikan ekspresi emosi yang sangat jujur dan mentah, sulit diungkapkan dengan kata-kata biasa. Perpaduan antara lirik yang intens tentang kehancuran diri, dan keinginan akan koneksi, dengan musik yang abrasif, menciptakan pengalaman katarsis bagi saya sendiri.

Mendengarkan ini mungkin seperti ada di pusat badai. Tapi intinya, ada keheningan. Semua orang bisa melewati kekacauan dalam keadaan utuh.

*Kamu pusatnya, bukan korbannya*.

## For My Beloveds

### Credo Quia Absurdum

{{< video https://youtu.be/cIi4SxZ0IC8?si=EeUQOrJCeDpnrkRK}}

> Through the torii of a weathered shrine, I pass
>
> There's no light but I’m dazzled nonetheless
>
> I feel I might drown in the winter sea,
>
> and it feels so gentle.

Lagu ber-subgenre favorit saya. Bassnya asik.

Seperti pengingat bahwa kenyamanan bisa muncul dari hal-hal yang tidak selalu hangat atau terang. Ada orang yang menemukan tenangnya di tengah keramaian, ada juga yang baru bisa bernapas saat dunia terasa hening. Ada ketenangan yang hanya bisa ditemukan lewat orang-orang yang kita sayangi, bukan karena mereka menghapus kekosongan, tapi karena mereka membuatnya terasa lebih hangat.

Tenggelam bukan selalu berarti hilang, kadang justru cara kita kembali merasa utuh, dan kehadiran seseorang juga bisa jadi tempat pulang.